/* created by click/linuxmodule/fixincludes.pl on Tue Nov 25 22:39:34 2014 */
/* from /lib/modules/2.6.27.5-117.fc10.i686/build/include/asm-generic/Kbuild */
#if defined(__cplusplus) && !CLICK_CXX_PROTECTED
# error "missing #include <click/cxxprotect.h>"
#endif
header-y += errno-base.h
header-y += errno.h
header-y += fcntl.h
header-y += ioctl.h
header-y += mman.h
header-y += poll.h
header-y += signal.h
header-y += statfs.h

unifdef-y += int-l64.h
unifdef-y += int-ll64.h
unifdef-y += resource.h
unifdef-y += siginfo.h
