/* created by click/linuxmodule/fixincludes.pl on Tue Nov 25 22:39:41 2014 */
/* from /lib/modules/2.6.27.5-117.fc10.i686/build/include/linux/usb/Kbuild */
#if defined(__cplusplus) && !CLICK_CXX_PROTECTED
# error "missing #include <click/cxxprotect.h>"
#endif
header-y += audio.h
header-y += cdc.h
header-y += ch9.h
header-y += gadgetfs.h
header-y += midi.h
header-y += g_printer.h

