/* created by click/linuxmodule/fixincludes.pl on Tue Nov 25 22:39:41 2014 */
/* from /lib/modules/2.6.27.5-117.fc10.i686/build/include/linux/dvb/Kbuild */
#if defined(__cplusplus) && !CLICK_CXX_PROTECTED
# error "missing #include <click/cxxprotect.h>"
#endif
header-y += ca.h
header-y += frontend.h
header-y += net.h
header-y += osd.h
header-y += version.h

unifdef-y += audio.h
unifdef-y += dmx.h
unifdef-y += video.h
